/* bienetre.js — Compétence « Bien-être » : boissons maison & petits rituels.
   PAS un cours à valider : une collection de recettes (cochables « déjà faite »)
   + des rituels bien-être. Injecté par assemble.js ; rendu par app.js. */
window.BIENETRE={
icon:'🌿', name:'Bien-être', color:'#5AA083',
meta:'Boissons maison, plats du pays & prise de masse',
cats:[
 {key:'boissons', label:'Boissons maison', ic:'🥤'},
 {key:'terroir',  label:'Recettes du coin — Bonnac & Ariège (09)', ic:'🍲'},
 {key:'masse',    label:'Prise de masse', ic:'💪'}
],
recettes:[
 {key:'bissap', ic:'🌺', t:'Bissap (jus d’hibiscus)', s:'La boisson reine : fleurs d’hibiscus infusées, fraîche et parfumée.',
  temps:'20 min + repos frais', pour:'≈ 1,5 L',
  ingr:['100 g de fleurs d’hibiscus séchées (bissap)','1,5 à 2 L d’eau','Sucre ou miel selon le goût (150–250 g)','1 sachet de sucre vanillé (ou 1 gousse de vanille)','Au choix : menthe fraîche, fleur d’oranger, jus de citron, gingembre, ananas'],
  etapes:['Rincer rapidement les fleurs d’hibiscus à l’eau claire.','Porter l’eau à frémissement, y jeter l’hibiscus, couper le feu et laisser infuser 15–30 min (plus c’est long, plus c’est corsé et acidulé).','Filtrer en pressant bien les fleurs.','Sucrer à chaud (le sucre se dissout mieux), ajouter la vanille et le parfum choisi.','Laisser refroidir, puis mettre au frais.','Servir très frais, avec des glaçons et une feuille de menthe.'],
  conseils:['Se garde 3–4 jours au réfrigérateur, dans une bouteille fermée.','Trop acidulé ? Rallonge d’eau et resucre. Trop fade ? Rallonge l’infusion la prochaine fois.'],
  anciens:['On ne fait JAMAIS bouillir l’hibiscus longtemps : on coupe le feu et on laisse infuser. Trop bouilli, il devient amer et perd sa belle couleur.','La menthe et la fleur d’oranger s’ajoutent APRÈS l’infusion, jamais pendant : sinon l’amertume prend le dessus.','Le secret des grands-mères : un bout de gingembre et une gousse de vanille dans l’infusion — et pour les jours de fête, un peu de jus d’ananas.','Les anciens laissent parfois infuser à froid, la jarre au soleil une demi-journée : le goût est plus rond, moins âpre.','On garde les fleurs pour une deuxième infusion, plus légère — on ne jette rien.','Ça se boit GLACÉ : au chaud, le bissap perd la moitié de son charme.']},
 {key:'gnamakoudji', ic:'🫚', t:'Jus de gingembre (gnamakoudji)', s:'Piquant et tonique, le cousin gingembre du bissap.',
  temps:'15 min + repos', pour:'≈ 1,5 L',
  ingr:['150 g de gingembre frais épluché','1,5 L d’eau','Le jus de 1–2 citrons','Sucre ou miel selon le goût','Au choix : vanille, fleur d’oranger, un peu d’ananas'],
  etapes:['Mixer le gingembre avec un peu d’eau jusqu’à obtenir une purée.','Ajouter le reste de l’eau, laisser reposer 15–20 min.','Filtrer à travers un linge fin en pressant bien.','Ajouter le jus de citron, sucrer, parfumer.','Servir bien frais — c’est fort, dose à ton goût.'],
  conseils:['Très concentré : on peut le boire allongé d’eau.','Réputé bon pour la digestion et un coup de fouet le matin.'] },
 {key:'menthe', ic:'🍵', t:'Thé à la menthe', s:'Le geste convivial : thé vert, menthe fraîche, bien sucré.',
  temps:'10 min', pour:'1 théière',
  ingr:['1 c. à soupe de thé vert (gunpowder)','1 gros bouquet de menthe fraîche','Sucre en morceaux selon le goût','Eau bouillante'],
  etapes:['Rincer le thé à l’eau chaude (jeter cette première eau, elle est amère).','Remettre le thé, ajouter l’eau bouillante, laisser infuser 3–4 min.','Ajouter la menthe et le sucre.','Verser de haut en versant-reversant dans les verres pour aérer et faire mousser.'],
  conseils:['Le geste de verser de haut fait la petite mousse : c’est la signature.','Deuxième et troisième infusion : chacune a son caractère.'] },
 {key:'golden', ic:'🟡', t:'Lait d’or (curcuma)', s:'Boisson chaude réconfortante, curcuma-gingembre, pour le soir.',
  temps:'10 min', pour:'2 tasses',
  ingr:['400 ml de lait (vache ou végétal)','1 c. à café de curcuma','½ c. à café de gingembre en poudre (ou frais râpé)','1 pincée de poivre noir (aide à assimiler le curcuma)','1 pincée de cannelle','Miel selon le goût'],
  etapes:['Verser le lait dans une casserole.','Ajouter curcuma, gingembre, poivre et cannelle.','Chauffer doucement en fouettant, sans faire bouillir, 3–5 min.','Sucrer au miel hors du feu, boire chaud.'],
  conseils:['La pincée de poivre n’est pas un détail : elle décuple l’effet du curcuma.','Parfait le soir, réconfortant et sans excitant.'] },
 {key:'citronnade', ic:'🍋', t:'Citronnade menthe-gingembre', s:'Ultra désaltérante pour les chaudes journées.',
  temps:'10 min', pour:'1,5 L',
  ingr:['Le jus de 4–5 citrons','1,5 L d’eau fraîche','1 morceau de gingembre râpé (facultatif)','1 bouquet de menthe','Sucre, miel ou sirop d’agave'],
  etapes:['Presser les citrons.','Mélanger jus, eau, gingembre et sucre jusqu’à dissolution.','Ajouter la menthe légèrement froissée.','Laisser reposer 15 min au frais, servir avec des glaçons.'],
  conseils:['Froisser la menthe (sans la déchirer) libère les arômes sans amertume.'] },
 {key:'tisane_soir', ic:'🌙', t:'Tisane du soir (détente)', s:'Le rituel avant de dormir : verveine, camomille, tilleul.',
  temps:'8 min', pour:'1 tasse',
  ingr:['1 c. à soupe de mélange verveine + camomille + tilleul (ou l’un des trois)','250 ml d’eau frémissante','Miel selon le goût'],
  etapes:['Chauffer l’eau sans la faire bouillir à gros bouillons.','Verser sur les plantes, couvrir, laisser infuser 5–7 min.','Filtrer, sucrer légèrement au miel.','Boire tranquillement, écrans éteints.'],
  conseils:['Couvrir pendant l’infusion garde les huiles essentielles apaisantes.','À boire 30–45 min avant le coucher.'] },
 {key:'digestion', ic:'🌱', t:'Infusion digestion', s:'Après un bon repas : menthe, gingembre, citron.',
  temps:'8 min', pour:'1 tasse',
  ingr:['Quelques feuilles de menthe fraîche','2–3 fines lamelles de gingembre','1 rondelle de citron','250 ml d’eau chaude'],
  etapes:['Mettre menthe, gingembre et citron dans la tasse.','Couvrir d’eau chaude, laisser infuser 5 min.','Boire chaud, après le repas.'],
  conseils:['Le trio menthe-gingembre-citron est le classique anti-lourdeurs.'] },
 {key:'detox', ic:'🥒', t:'Eau infusée fraîcheur', s:'Pour boire plus d’eau sans s’ennuyer : concombre, citron, menthe.',
  temps:'5 min + 1 h au frais', pour:'1 L',
  ingr:['1 L d’eau fraîche','½ concombre en rondelles','½ citron en rondelles','Quelques feuilles de menthe','Facultatif : quelques fruits rouges'],
  etapes:['Mettre tous les ingrédients dans une carafe.','Laisser infuser au moins 1 h au réfrigérateur.','Boire dans la journée, recharger d’eau 1 fois.'],
  conseils:['Le truc le plus simple pour boire assez d’eau quand il fait chaud ou qu’on travaille dehors.'] },
 {key:'smoothie', ic:'🍌', t:'Smoothie banane-avoine', s:'Un petit-déj complet à boire, rassasiant et doux.',
  temps:'5 min', pour:'1 grand verre',
  ingr:['1 banane bien mûre','3 c. à soupe de flocons d’avoine','200 ml de lait (ou boisson végétale)','1 c. à café de miel','1 pincée de cannelle','Facultatif : 1 c. à soupe de beurre de cacahuète'],
  etapes:['Mettre tous les ingrédients dans un blender.','Mixer jusqu’à consistance lisse.','Boire aussitôt, bien frais.'],
  conseils:['L’avoine cale pour toute la matinée — idéal avant une journée de chantier.'] },
 /* ---- Recettes du coin — Bonnac & Ariège (09) ---- */
 {key:'azinat', cat:'terroir', ic:'🥘', t:'Azinat (potée ariégeoise)', s:'Le plat emblématique de l’Ariège : chou, légumes et viandes mijotés.',
  temps:'2 h 30', pour:'6 personnes',
  ingr:['1 chou vert','6 pommes de terre','4 carottes','2 navets','1 poireau','1 talon de jambon (ou palette de porc)','1 saucisse à cuire / saucisson de couenne','2 cuisses de confit de canard','1 rouzole (voir recette)','Sel, poivre, 1 bouquet garni'],
  etapes:['Blanchir le chou coupé 5 min à l’eau bouillante, égoutter.','Dans un grand faitout, couvrir d’eau le jambon et la saucisse, porter à frémissement, écumer.','Ajouter chou, carottes, navets, poireau et le bouquet garni ; mijoter 1 h 30 à petit feu.','Ajouter les pommes de terre et la rouzole, poursuivre 30–40 min.','Réchauffer le confit à part, l’ajouter en fin de cuisson.','Servir d’abord le bouillon sur du pain (l’« oulade »), puis les légumes et les viandes.'],
  conseils:['Encore meilleur réchauffé le lendemain.'],
  note:'Plat traditionnel ariégeois — chaque famille a sa version. Donne-moi celle de chez toi à Bonnac et je la remplace.'},
 {key:'rouzole', cat:'terroir', ic:'🫓', t:'Rouzole', s:'La galette de pain et de lard qui accompagne l’azinat.',
  temps:'20 min', pour:'4–6 personnes',
  ingr:['200 g de mie de pain rassis','150 g de ventrèche / lard + jambon hachés','2 œufs','2 gousses d’ail','1 bouquet de persil','Sel, poivre','Graisse de canard pour la poêle'],
  etapes:['Émietter la mie de pain, mélanger avec le lard et le jambon hachés, l’ail et le persil ciselés.','Lier avec les œufs, saler, poivrer.','Former une grosse galette épaisse.','La dorer à la poêle dans la graisse de canard, des deux côtés.','La plonger dans l’azinat en fin de cuisson (ou la manger telle quelle).']},
 {key:'mounjetado', cat:'terroir', ic:'🍲', t:'Mounjetado (cassoulet ariégeois)', s:'Le cassoulet de l’Ariège aux mongettes (haricots) et au confit.',
  temps:'3 h + trempage', pour:'6 personnes',
  ingr:['500 g de haricots secs (mongettes / lingots), trempés une nuit','4 cuisses de confit de canard','300 g de saucisse de Toulouse','200 g de couenne','1 talon de jambon','2 carottes, 1 oignon piqué de clous de girofle','2 gousses d’ail, 1 bouquet garni','Sel, poivre'],
  etapes:['Cuire les haricots égouttés avec couenne, jambon, carottes, oignon et bouquet garni, 1 h 30 à frémissement.','Faire dorer la saucisse, réchauffer le confit.','Dans un plat à cassoulet, alterner haricots, viandes et couenne.','Mouiller avec le bouillon des haricots.','Enfourner à 150 °C 1 h à 1 h 30 : casser la croûte qui se forme et la remouiller plusieurs fois.'],
  conseils:['La graisse du confit fait tout le moelleux.','« Casser la croûte » 7 fois, dit la tradition.']},
 {key:'millas', cat:'terroir', ic:'🌽', t:'Millas', s:'La galette de farine de maïs — sucrée au petit-déj, ou salée avec la potée.',
  temps:'40 min + repos', pour:'4–6 personnes',
  ingr:['250 g de farine de maïs','1 L d’eau (ou moitié lait)','50 g de beurre ou de graisse de canard','1 pincée de sel','Sucre pour la version sucrée'],
  etapes:['Porter l’eau salée à ébullition avec le beurre.','Verser la farine de maïs en pluie en fouettant, sans grumeaux.','Cuire 20–30 min à feu doux en remuant : la bouillie épaissit.','Étaler sur ~1,5 cm sur un plan huilé, laisser refroidir et prendre.','Découper en losanges et poêler jusqu’à ce que ce soit doré.','Sucrer (version sucrée) ou servir avec la potée (version salée).']},
 {key:'croustade', cat:'terroir', ic:'🥧', t:'Croustade aux pommes', s:'Le dessert du pays d’oc : pommes, pâte fine et un trait d’armagnac.',
  temps:'1 h', pour:'6–8 parts',
  ingr:['6 pommes','1 paquet de pâte filo (ou pâte à croustade)','100 g de sucre','100 g de beurre fondu','1 sachet de sucre vanillé','1 trait d’armagnac (facultatif)'],
  etapes:['Peler et couper les pommes en fines lamelles, les revenir avec sucre, vanille et armagnac.','Beurrer plusieurs feuilles de filo, en tapisser un moule en les laissant déborder.','Garnir de pommes, replier les feuilles en chiffonnade par-dessus.','Beurrer et sucrer le dessus.','Enfourner 25–30 min à 180 °C jusqu’à doré et croustillant.']},
 {key:'coque_pamiers', cat:'terroir', ic:'🍞', t:'Coque de Pamiers', s:'La brioche à la fleur d’oranger, spécialité de Pamiers — juste à côté de Bonnac.',
  temps:'3 h (levées)', pour:'1 grande coque',
  ingr:['500 g de farine','100 g de beurre mou','100 g de sucre','2 œufs','20 cl de lait tiède','1 sachet de levure de boulanger','2 c. à soupe de fleur d’oranger','1 pincée de sel','Le zeste d’1 citron','Fruits confits (facultatif)'],
  etapes:['Délayer la levure dans le lait tiède.','Pétrir farine, sucre, sel, œufs, beurre, fleur d’oranger, zeste et le lait à la levure en pâte souple.','Laisser lever 1 h 30 (volume doublé).','Former une couronne aplatie (la « coque »), laisser lever encore 45 min.','Dorer à l’œuf, parsemer de sucre (et de fruits confits).','Cuire 25–30 min à 180 °C.'],
  note:'La coque de Pamiers est LA spécialité toute proche de Bonnac. Si ta famille a sa recette, je la remplace par la tienne.'},
 /* ---- Prise de masse ---- */
 {key:'omelette', cat:'masse', ic:'🍳', t:'Omelette costaud', s:'Beaucoup de protéines, prêtes en 10 minutes.', apport:'≈ 35 g de protéines',
  temps:'10 min', pour:'1 personne',
  ingr:['4 à 6 œufs','50 g de fromage râpé','2 tranches de jambon ou de blanc de dinde','Poivron, oignon, épinards','Sel, poivre','1 filet d’huile d’olive'],
  etapes:['Battre les œufs, saler, poivrer.','Faire revenir les légumes et le jambon coupés.','Verser les œufs, ajouter le fromage.','Cuire à feu moyen, plier et servir.'],
  conseils:['Ajoute du pain complet ou du riz pour les glucides.']},
 {key:'poulet_riz', cat:'masse', ic:'🍗', t:'Poulet, riz & brocoli', s:'Le classique de la prise de masse : protéines + glucides + légumes.', apport:'≈ 50 g de protéines',
  temps:'25 min', pour:'1–2 personnes',
  ingr:['200 g de blanc de poulet','80 g de riz (cru)','1 brocoli','1 c. à soupe d’huile d’olive','Ail, paprika, sel, poivre','Sauce soja (facultatif)'],
  etapes:['Cuire le riz.','Couper le poulet, le poêler avec ail et paprika jusqu’à cuisson complète.','Cuire le brocoli à la vapeur 6–8 min.','Assembler et assaisonner.']},
 {key:'oeufs_avoine', cat:'masse', ic:'🥣', t:'Petit-déj œufs-avoine', s:'Un petit-déjeuner protéiné qui tient toute la matinée.', apport:'≈ 30 g de protéines',
  temps:'10 min', pour:'1 personne',
  ingr:['3 œufs','60 g de flocons d’avoine','250 ml de lait','1 banane','1 c. à soupe de miel','Cannelle'],
  etapes:['Cuire les flocons dans le lait 3–4 min (porridge).','Ajouter la banane écrasée, le miel et la cannelle.','Servir avec des œufs brouillés ou durs à côté.']},
 {key:'poulet_patate', cat:'masse', ic:'🍠', t:'Poêlée poulet-patate douce', s:'Complet et rassasiant, avec des glucides lents.', apport:'≈ 45 g de protéines',
  temps:'30 min', pour:'2 personnes',
  ingr:['300 g de poulet','2 patates douces','200 g de haricots verts','Huile d’olive','Curry ou paprika, sel, poivre'],
  etapes:['Couper et rôtir les patates douces (four 200 °C, 25 min, ou à la poêle).','Poêler le poulet.','Cuire les haricots à la vapeur.','Mélanger et assaisonner.']},
 {key:'shake_masse', cat:'masse', ic:'🥤', t:'Shake maison prise de masse', s:'La collation liquide qui remplace un gainer.', apport:'≈ 40 g de protéines',
  temps:'5 min', pour:'1 grand verre',
  ingr:['400 ml de lait','1 banane','60 g de flocons d’avoine','2 c. à soupe de beurre de cacahuète','1 œuf (ou 30 g de whey)','1 c. à café de miel'],
  etapes:['Mettre tous les ingrédients au blender.','Mixer jusqu’à consistance lisse.','Boire après l’entraînement ou en collation.'],
  conseils:['Œuf cru : préfère du blanc pasteurisé ou de la whey si tu veux éviter tout risque (salmonelle).']},
 {key:'boeuf_pates', cat:'masse', ic:'🍝', t:'Bœuf haché, pâtes & légumes', s:'Un plat costaud et facile, riche en protéines.', apport:'≈ 45 g de protéines',
  temps:'25 min', pour:'2 personnes',
  ingr:['250 g de bœuf haché (5 % MG)','150 g de pâtes (cru)','1 boîte de tomates concassées','1 oignon, 2 gousses d’ail','1 courgette ou 1 poivron','Huile d’olive, herbes, sel, poivre'],
  etapes:['Cuire les pâtes.','Faire revenir oignon, ail et légumes.','Ajouter le bœuf, faire dorer, puis les tomates ; mijoter 10 min.','Servir sur les pâtes.']},
 {key:'riz_cantonais', cat:'masse', ic:'🍚', t:'Riz cantonais protéiné', s:'Un plat complet et parfait pour vider le frigo.', apport:'≈ 35 g de protéines',
  temps:'20 min', pour:'2 personnes',
  ingr:['200 g de riz (cru)','3 œufs','150 g de blanc de poulet ou de jambon','100 g de petits pois','2 oignons nouveaux','Sauce soja, huile'],
  etapes:['Cuire le riz, le laisser refroidir.','Brouiller les œufs, réserver.','Sauter le poulet et les petits pois.','Ajouter le riz, les œufs et la sauce soja ; faire sauter.','Parsemer d’oignons nouveaux.']}
],
astuces:[
 {cat:'Bien boire, bien se sentir', ic:'💧', items:[
  {t:'Bois avant d’avoir soif', d:'La soif, c’est déjà un début de déshydratation. Une gourde à portée, quelques gorgées régulières : l’eau infusée aide à en boire plus sans y penser.'},
  {t:'Le froid réveille, le chaud apaise', d:'Bissap, citronnade et eau infusée pour la fraîcheur et l’énergie ; tisane du soir et lait d’or pour se poser et préparer le sommeil.'},
  {t:'Sucre : dose à la baisse', d:'Réduis le sucre petit à petit sur quelques semaines — le palais s’habitue, et on savoure mieux le vrai goût des plantes et des fruits.'},
  {t:'Le gingembre, ton allié', d:'Un coup de fouet le matin (gnamakoudji), un coup de main à la digestion le soir : le même rhizome, deux usages.'}
 ]},
 {cat:'Petits rituels qui font du bien', ic:'🧘', items:[
  {t:'Respire en 365', d:'3 fois par jour, 6 respirations par minute, pendant 5 minutes (inspire 5 s / expire 5 s). La cohérence cardiaque calme le stress en quelques minutes.'},
  {t:'Bouge un peu, souvent', d:'Une marche de 10–15 min après le repas vaut mieux qu’une grosse séance rare : ça aide la digestion, la tête et le dos.'},
  {t:'Un sommeil régulier', d:'Se coucher et se lever à heures proches, même le week-end. Écrans éteints 30 min avant, une tisane, et la chambre au frais.'},
  {t:'Le matin sans écran', d:'Les 15 premières minutes réveillées sans téléphone : un verre d’eau, s’étirer, respirer — la journée démarre plus calme.'},
  {t:'La lumière du dehors', d:'Quelques minutes dehors le matin (même gris) calent l’horloge interne et améliorent l’humeur et le sommeil du soir.'}
 ]}
]
};
