/* elagage_guide.js — Guide d'élagage par arbre (onglet permanent du domaine Élagage). */
window.ELAG_GUIDE=[
 {cat:'Feuillus durs', arbres:[
  {n:'Chêne', ic:'🌳', per:'Fin d’hiver hors gel · éviter avril-mai', tol:'Bonne (lent à réagir)',
   meth:['Taille douce au col, petites sections','Élagage de formation des jeunes sujets (axe dominant)','Peut se conduire en trogne/têtard (tradition)','Suppression du bois mort sans urgence : il tient des années'],
   warn:'Grosses coupes = pourriture lente mais certaine. Le chêne pardonne l’attente : mieux vaut deux passages doux qu’un massacre.'},
  {n:'Hêtre', ic:'🌳', per:'Fin d’été (taille en vert) ou fin d’hiver', tol:'Faible sur grosses coupes',
   meth:['Taille douce uniquement, sections < 5 cm','Élaguer tôt : la formation fait tout','Peut se conduire en haie plessée ou rideau'],
   warn:'Écorce fine : les grosses plaies et le soleil direct la brûlent (écorce qui éclate). Jamais d’étêtage.'},
  {n:'Frêne', ic:'🌳', per:'Fin d’hiver · éviter la montée de sève', tol:'Bonne',
   meth:['Trogne/têtard traditionnel (feuillard, fourrage)','Taille douce au col','Formation facile : réagit vite et droit'],
   warn:'Surveille la chalarose (dessèchement des rameaux) : ne taille pas un frêne malade sans avis, et désinfecte les outils.'},
  {n:'Charme', ic:'🌳', per:'Fin d’hiver, et été pour les haies', tol:'Excellente',
   meth:['Supporte la taille répétée : haies, charmilles, plessage','Trogne possible','Taille douce partout'],
   warn:'Quasi aucun piège : le champion de la taille. Garde des sections modestes, c’est tout.'},
  {n:'Robinier', ic:'🌳', per:'Fin d’été de préférence', tol:'Bonne mais drageonne',
   meth:['Taille douce ; recépage possible (repart de souche très fort)','Conduite en cépée pour piquets'],
   warn:'Épines + bois très dur : chaîne affûtée et gants épais. Chaque coupe déclenche drageons et rejets vigoureux.'}]},
 {cat:'Feuillus à bois tendre ou « pleureurs »', arbres:[
  {n:'Bouleau', ic:'🌲', per:'Fin d’été UNIQUEMENT (jamais fin d’hiver)', tol:'Faible',
   meth:['Taille minimale : bois mort et branches gênantes','Sections < 5 cm au col'],
   warn:'Pleureur extrême : taillé en fin d’hiver il « saigne » des litres de sève. Grosses coupes = pourriture rapide.'},
  {n:'Peuplier', ic:'🌲', per:'Fin d’été / automne sec', tol:'Moyenne (bois cassant)',
   meth:['Élagage de billes pour le sciage (branches basses tôt)','Têtard traditionnel possible','Surveillance du bois mort : il casse net'],
   warn:'Branches lourdes et cassantes : rétention obligatoire au démontage, et ne jamais travailler dessous par vent.'},
  {n:'Noyer', ic:'🌰', per:'Fin d’été (août-septembre), par temps sec', tol:'Faible',
   meth:['Le moins possible : formation jeune, puis bois mort','Coupe en 3 temps stricte, sections mini'],
   warn:'Pleureur et rancunier : les grosses plaies ne se ferment pas. On forme jeune pour ne jamais retailler adulte.'},
  {n:'Merisier', ic:'🍒', per:'Fin d’été, par temps sec', tol:'Faible',
   meth:['Taille douce d’éclaircie, sections < 4-5 cm','Élagage de formation pour bille droite (bois précieux)'],
   warn:'Gomme et maladies (gommose, cylindrospora) : outils propres, temps sec obligatoire, jamais en hiver humide.'}]},
 {cat:'Résineux', arbres:[
  {n:'Pin sylvestre', ic:'🌲', per:'Fin d’été / automne, à sec', tol:'Faible (pas de rejet)',
   meth:['Élagage des branches basses mortes (élagage « à sec » des billes)','Jamais plus du tiers vivant','Taille de formation légère seulement'],
   warn:'Un résineux ne « repousse » pas où on coupe : pas de réitération. Toute coupe est définitive, la résine coule au printemps.'},
  {n:'Épicéa', ic:'🌲', per:'Automne, à sec', tol:'Très faible',
   meth:['Branches basses mortes uniquement','Haies : tailles légères et régulières, jamais dans le vieux bois'],
   warn:'Taillé dans le vieux bois, il ne reverdit JAMAIS. Racines superficielles : ne pas dégarnir un côté (prise au vent).'},
  {n:'Sapin', ic:'🌲', per:'Automne, à sec', tol:'Très faible',
   meth:['Bois mort et branches basses','Respect absolu de la flèche (tête) unique'],
   warn:'Comme l’épicéa : pas de coupe dans le vieux bois. Si la flèche casse, en sélectionner une seule de remplacement.'},
  {n:'Douglas', ic:'🌲', per:'Fin d’été / automne', tol:'Faible',
   meth:['Élagage des billes à 6 m pour le bois d’œuvre (branches < 3 cm, à sec de préférence)','Formation : une seule flèche'],
   warn:'Élague tôt et petit : les nœuds sont l’ennemi de son bois d’œuvre. Jamais d’étêtage.'},
  {n:'Mélèze', ic:'🌲', per:'Automne (après chute des aiguilles)', tol:'Faible',
   meth:['Branches basses pour la bille','Taille légère de formation'],
   warn:'Seul résineux à perdre ses aiguilles : taille-le nu, en automne. Mêmes règles : petit, définitif.'}]},
 {cat:'Fruitiers (verger)', arbres:[
  {n:'Pommier / Poirier', ic:'🍎', per:'Hiver hors gel (fruitiers à pépins) + taille en vert en été', tol:'Bonne',
   meth:['Taille de fructification : aérer le centre (gobelet), raccourcir sur œil extérieur','Taille trigemme classique','Éclaircissage des fruits en juin'],
   warn:'Alterne : une taille sévère = du bois, pas des fruits. Vise la lumière au centre, sections petites.'},
  {n:'Cerisier / Prunier', ic:'🍒', per:'ÉTÉ uniquement (après récolte), temps sec', tol:'Faible',
   meth:['Le strict nécessaire : bois mort, branches croisées','Coupe en 3 temps, plaies mini'],
   warn:'Fruitiers à noyau = gommose : toute taille d’hiver les fait couler et s’infecter. L’été, plaie sèche = arbre sain.'},
  {n:'Noisetier', ic:'🌰', per:'Fin d’hiver', tol:'Excellente',
   meth:['Recépage par tiers : couper au sol 1/3 des plus vieilles tiges chaque année','Conduite en cépée aérée'],
   warn:'Ne taille pas « en arbre » : c’est une cépée. Le recépage tournant le rajeunit indéfiniment.'}]}
];
