/* elagage_guide.js — Guide d'élagage par arbre (onglet permanent du domaine Élagage). */
window.ELAG_GUIDE=[
 {cat:'Feuillus durs', arbres:[
  {n:'Chêne', ic:'🌳', per:'Fin d’hiver hors gel · éviter avril-mai', tol:'Bonne (lent à réagir)',
   meth:['Taille douce au col, petites sections','Élagage de formation des jeunes sujets (axe dominant)','Peut se conduire en trogne/têtard (tradition)','Suppression du bois mort sans urgence : il tient des années'],
   warn:'Grosses coupes = pourriture lente mais certaine. Le chêne pardonne l’attente : mieux vaut deux passages doux qu’un massacre.'},
  {n:'Hêtre', ic:'🌳', per:'Fin d’été (taille en vert) ou fin d’hiver', tol:'Faible sur grosses coupes',
   meth:['Taille douce uniquement, sections < 5 cm','Élaguer tôt : la formation fait tout','Peut se conduire en haie plessée ou rideau'],
   warn:'Écorce fine : les grosses plaies et le soleil direct la brûlent (écorce qui éclate). Jamais d’étêtage.'},
  {n:'Frêne', ic:'🌳', per:'Fin d’hiver · éviter la montée de sève', tol:'Bonne',
   meth:['Trogne/têtard traditionnel (feuillard, fourrage)','Taille douce au col','Formation facile : réagit vite et droit'],
   warn:'Surveille la chalarose (dessèchement des rameaux) : ne taille pas un frêne malade sans avis, et désinfecte les outils.'},
  {n:'Charme', ic:'🌳', per:'Fin d’hiver, et été pour les haies', tol:'Excellente',
   meth:['Supporte la taille répétée : haies, charmilles, plessage','Trogne possible','Taille douce partout'],
   warn:'Quasi aucun piège : le champion de la taille. Garde des sections modestes, c’est tout.'},
  {n:'Robinier', ic:'🌳', per:'Fin d’été de préférence', tol:'Bonne mais drageonne',
   meth:['Taille douce ; recépage possible (repart de souche très fort)','Conduite en cépée pour piquets'],
   warn:'Épines + bois très dur : chaîne affûtée et gants épais. Chaque coupe déclenche drageons et rejets vigoureux.'}]},
 {cat:'Feuillus à bois tendre ou « pleureurs »', arbres:[
  {n:'Bouleau', ic:'🌲', per:'Fin d’été UNIQUEMENT (jamais fin d’hiver)', tol:'Faible',
   meth:['Taille minimale : bois mort et branches gênantes','Sections < 5 cm au col'],
   warn:'Pleureur extrême : taillé en fin d’hiver il « saigne » des litres de sève. Grosses coupes = pourriture rapide.'},
  {n:'Peuplier', ic:'🌲', per:'Fin d’été / automne sec', tol:'Moyenne (bois cassant)',
   meth:['Élagage de billes pour le sciage (branches basses tôt)','Têtard traditionnel possible','Surveillance du bois mort : il casse net'],
   warn:'Branches lourdes et cassantes : rétention obligatoire au démontage, et ne jamais travailler dessous par vent.'},
  {n:'Noyer', ic:'🌰', per:'Fin d’été (août-septembre), par temps sec', tol:'Faible',
   meth:['Le moins possible : formation jeune, puis bois mort','Coupe en 3 temps stricte, sections mini'],
   warn:'Pleureur et rancunier : les grosses plaies ne se ferment pas. On forme jeune pour ne jamais retailler adulte.'},
  {n:'Merisier', ic:'🍒', per:'Fin d’été, par temps sec', tol:'Faible',
   meth:['Taille douce d’éclaircie, sections < 4-5 cm','Élagage de formation pour bille droite (bois précieux)'],
   warn:'Gomme et maladies (gommose, cylindrospora) : outils propres, temps sec obligatoire, jamais en hiver humide.'}]},
 {cat:'Résineux', arbres:[
  {n:'Pin sylvestre', ic:'🌲', per:'Fin d’été / automne, à sec', tol:'Faible (pas de rejet)',
   meth:['Élagage des branches basses mortes (élagage « à sec » des billes)','Jamais plus du tiers vivant','Taille de formation légère seulement'],
   warn:'Un résineux ne « repousse » pas où on coupe : pas de réitération. Toute coupe est définitive, la résine coule au printemps.'},
  {n:'Épicéa', ic:'🌲', per:'Automne, à sec', tol:'Très faible',
   meth:['Branches basses mortes uniquement','Haies : tailles légères et régulières, jamais dans le vieux bois'],
   warn:'Taillé dans le vieux bois, il ne reverdit JAMAIS. Racines superficielles : ne pas dégarnir un côté (prise au vent).'},
  {n:'Sapin', ic:'🌲', per:'Automne, à sec', tol:'Très faible',
   meth:['Bois mort et branches basses','Respect absolu de la flèche (tête) unique'],
   warn:'Comme l’épicéa : pas de coupe dans le vieux bois. Si la flèche casse, en sélectionner une seule de remplacement.'},
  {n:'Douglas', ic:'🌲', per:'Fin d’été / automne', tol:'Faible',
   meth:['Élagage des billes à 6 m pour le bois d’œuvre (branches < 3 cm, à sec de préférence)','Formation : une seule flèche'],
   warn:'Élague tôt et petit : les nœuds sont l’ennemi de son bois d’œuvre. Jamais d’étêtage.'},
  {n:'Mélèze', ic:'🌲', per:'Automne (après chute des aiguilles)', tol:'Faible',
   meth:['Branches basses pour la bille','Taille légère de formation'],
   warn:'Seul résineux à perdre ses aiguilles : taille-le nu, en automne. Mêmes règles : petit, définitif.'}]},
 {cat:'Fruitiers (verger)', arbres:[
  {n:'Pommier / Poirier', ic:'🍎', per:'Hiver hors gel (fruitiers à pépins) + taille en vert en été', tol:'Bonne',
   meth:['Taille de fructification : aérer le centre (gobelet), raccourcir sur œil extérieur','Taille trigemme classique','Éclaircissage des fruits en juin'],
   warn:'Alterne : une taille sévère = du bois, pas des fruits. Vise la lumière au centre, sections petites.'},
  {n:'Cerisier / Prunier', ic:'🍒', per:'ÉTÉ uniquement (après récolte), temps sec', tol:'Faible',
   meth:['Le strict nécessaire : bois mort, branches croisées','Coupe en 3 temps, plaies mini'],
   warn:'Fruitiers à noyau = gommose : toute taille d’hiver les fait couler et s’infecter. L’été, plaie sèche = arbre sain.'},
  {n:'Noisetier', ic:'🌰', per:'Fin d’hiver', tol:'Excellente',
   meth:['Recépage par tiers : couper au sol 1/3 des plus vieilles tiges chaque année','Conduite en cépée aérée'],
   warn:'Ne taille pas « en arbre » : c’est une cépée. Le recépage tournant le rajeunit indéfiniment.'},
  {n:'Pêcher', ic:'🍑', per:'Sortie d’hiver (bouton rose) ou en vert après récolte, à sec', tol:'Exige une taille annuelle',
   meth:['Renouveler le bois : il fructifie sur les rameaux de l’an passé','Tailler assez long (garder des rameaux mixtes), ôter le vieux bois épuisé','Former en gobelet aéré, centre ouvert'],
   warn:'À noyau = cloque et gommose : temps sec, outils propres, jamais en hiver humide. Sans taille annuelle il s’épuise et se dégarnit.'},
  {n:'Abricotier', ic:'🍑', per:'Été, après récolte, par temps sec et chaud', tol:'Faible (gommose / moniliose)',
   meth:['Le strict minimum : bois mort, branches mal placées, éclaircie légère','Former jeune en gobelet, sections petites'],
   warn:'Champion des maladies de plaie : jamais de taille en hiver. Coupe l’été sec, désinfecte, protège les grosses plaies.'},
  {n:'Amandier', ic:'🌰', per:'Été après récolte, à sec', tol:'Faible (noyau)',
   meth:['Léger : aérer le centre, bois mort, remonter les branches basses','Former jeune ; il fructifie sur rameaux de l’an passé et bouquets'],
   warn:'Floraison très précoce et bois à noyau : gommose et moniliose. Pas de grosses coupes en hiver humide.'},
  {n:'Figuier', ic:'🌿', per:'Fin d’hiver (fév-mars), hors gel', tol:'Bonne',
   meth:['Aérer et limiter la hauteur pour cueillir à la main','Rabattre les branches trop longues sur un œil, ôter rejets et bois mort','Adapter selon variété unifère / bifère'],
   warn:'Latex blanc irritant : gants et manches longues. Sur variété à deux récoltes, ne rase pas le vieux bois porteur des figues-fleurs.'},
  {n:'Vigne', ic:'🍇', per:'Plein hiver, au repos (déc-févr)', tol:'Excellente (taille indispensable)',
   meth:['Taille Guyot (une baguette + un courson) ou gobelet (coursons à 2 yeux)','Ne garder que quelques yeux : on maîtrise sévèrement','Ébourgeonnage et rognage en vert l’été'],
   warn:'Taillée trop tard, elle « pleure » la sève. Sans taille sévère : beaucoup de bois, peu de raisin.'},
  {n:'Olivier', ic:'🫒', per:'Printemps (mars-avril), après les gelées, avant floraison', tol:'Bonne',
   meth:['Gobelet ouvert : la lumière au centre (« qu’un oiseau puisse le traverser »)','Ôter gourmands, rejets de souche et branches qui plongent','Fructifie sur le bois de l’an passé : ne pas tout raccourcir'],
   warn:'Craint le gel : ne pas tailler avant les dernières gelées. On éclaircit sans décapiter.'},
  {n:'Kiwi (actinidia)', ic:'🥝', per:'Cœur de l’hiver (déc-janv), bien avant la sève', tol:'Bonne mais pleure',
   meth:['Palissage sur fils ; garder des coursons à quelques yeux','Taille d’hiver de fructification + rognage en vert l’été','Prévoir un pied mâle pour la pollinisation'],
   warn:'Comme la vigne : taillé tard il « pleure » abondamment. Liane vigoureuse : palissage costaud obligatoire.'},
  {n:'Cognassier', ic:'🍐', per:'Hiver hors gel', tol:'Bonne',
   meth:['Comme un fruitier à pépins : gobelet aéré, centre éclairci','Raccourcir modérément ; il fructifie au bout des pousses','Supprimer les drageons de souche'],
   warn:'Sensible à la moniliose et au feu bactérien : outils propres, ôte et brûle le bois atteint.'},
  {n:'Kaki (plaqueminier)', ic:'🟠', per:'Fin d’hiver hors gel', tol:'Moyenne (bois cassant)',
   meth:['Éclaircir et limiter la hauteur','Alléger / étayer les branches chargées avant récolte','Fructifie sur pousses de l’année : taille modérée'],
   warn:'Bois cassant sous le poids des fruits : allège avant que ça casse. Les grosses coupes cicatrisent mal.'},
  {n:'Petits fruits (cassis, groseillier, framboisier)', ic:'🫐', per:'Fin d’hiver ; framboisier aussi après récolte', tol:'Excellente',
   meth:['Cassis / groseillier : recéper au sol les branches de plus de 3 ans','Framboisier non remontant : couper les cannes ayant fructifié','Remontant : rabattre selon la récolte voulue'],
   warn:'Ce sont des buissons, pas des arbres : on renouvelle les tiges, on ne « taille pas en arbre ».'}]}
];

/* Calendrier de taille du verger, mois par mois (climat tempéré / Ariège). */
window.ELAG_CALENDAR=[
 {m:'Janvier', ic:'❄️', sais:'Plein repos', taille:['Fruitiers à PÉPINS (pommier, poirier, cognassier) : taille d’hiver, hors gel','Vigne au repos (Guyot / gobelet)','Kiwi (actinidia), bien avant la sève'], a:['Brûler ou broyer le bois de taille','Badigeon / bouillie bordelaise sur plaies et troncs'], evit:'Ne pas tailler par gel fort (< −4 °C) ni les arbres à NOYAU.'},
 {m:'Février', ic:'🌫️', sais:'Fin de repos', taille:['Finir la taille des à pépins, de la vigne et du kiwi AVANT le débourrement','Petits fruits : recéper cassis/groseillier, cannes du framboisier'], a:['Traitement d’hiver (huile, bouillie) par temps doux et sec','Préparer greffons'], evit:'Toujours pas de taille des à noyau ; attention à la montée de sève qui approche.'},
 {m:'Mars', ic:'🌱', sais:'Débourrement', taille:['Dernier délai pour les à pépins et la vigne avant l’ouverture des bourgeons','Olivier en fin de mois, une fois les fortes gelées passées'], a:['Plantation des fruitiers à racines nues (si sol non gelé)','Griffage et fumure au pied'], evit:'Une fois les bourgeons ouverts, on arrête la taille de structure.'},
 {m:'Avril', ic:'🌸', sais:'Floraison', taille:['Presque plus rien : on respecte la floraison','Finir l’olivier si besoin'], a:['Surveiller les gelées tardives (voiles)','Palisser les jeunes pousses'], evit:'Ne pas tailler en pleine fleur : on gaspille la récolte et on stresse l’arbre.'},
 {m:'Mai', ic:'🍃', sais:'Croissance', taille:['Début de la TAILLE EN VERT : ébourgeonnage, épamprage de la vigne, pincement du pêcher','Supprimer les gourmands à la main'], a:['Début de l’éclaircissage des fruits (fin de mois)','Attacher / palisser'], evit:'Pas de grosses coupes : on guide les pousses tendres, c’est tout.'},
 {m:'Juin', ic:'☀️', sais:'Taille en vert', taille:['Taille en vert des formes palissées (pommier, poirier)','Vigne : rognage, épamprage, effeuillage léger'], a:['Éclaircissage des fruits (pommier/poirier) : garder 1 fruit par bouquet','Chute physiologique de juin : laisser faire'], evit:'On aère pour la lumière, sans décapiter les charpentières.'},
 {m:'Juillet', ic:'🌤️', sais:'Été sec', taille:['CERISIER et fruitiers à noyau précoces : taille APRÈS récolte, par temps sec','Pêcher : taille en vert après les premières récoltes','Rognage de la vigne'], a:['Éclaircir encore si surcharge','Arrosage des jeunes plantations'], evit:'Éviter de tailler en pleine canicule aux heures chaudes (stress, coups de soleil sur l’écorce).'},
 {m:'Août', ic:'🌾', sais:'LE mois des noyaux', taille:['Fruitiers à NOYAU (cerisier, prunier, abricotier, pêcher, amandier) : taille d’été après récolte, à sec','Taille en vert des pépins palissés'], a:['Récoltes','Marcotter, préparer les greffes en écusson'], evit:'C’est LE bon moment pour les à noyau : plaie sèche = arbre sain. Jamais en hiver humide.'},
 {m:'Septembre', ic:'🍂', sais:'Fin d’été', taille:['Finir les à noyau si le temps reste sec','Nettoyage du bois mort et des branches cassées'], a:['Grosses récoltes (pommes, poires, raisin)','Ramasser les fruits momifiés (moniliose)'], evit:'Si l’humidité revient, on stoppe la taille des à noyau.'},
 {m:'Octobre', ic:'🍁', sais:'Chute des feuilles', taille:['Peu de taille : on laisse l’arbre entrer en repos','Bois mort et branches dangereuses seulement'], a:['Préparer les trous de plantation','Récolte des fruits tardifs et du kaki'], evit:'On attend la vraie descente de sève avant la taille d’hiver.'},
 {m:'Novembre', ic:'🌧️', sais:'Entrée en repos', taille:['Après la chute des feuilles : reprise possible de la taille des à PÉPINS si temps doux','Recépage des petits fruits'], a:['Plantation (« à la Sainte-Catherine, tout bois prend racine », 25 nov.)','Badigeon des troncs'], evit:'Ne pas tailler les à noyau ni par temps de gel.'},
 {m:'Décembre', ic:'⛄', sais:'Repos', taille:['Taille d’hiver des à PÉPINS et de la VIGNE, dès qu’il ne gèle pas','Kiwi en fin de mois'], a:['Entretien et affûtage des outils','Vérifier tuteurs et attaches'], evit:'Par gel fort, on range les sécateurs : le bois gelé éclate et cicatrise mal.'}
];

/* Variétés fruitières locales de l'Ariège / piémont pyrénéen.
   Sélection documentée (associations & conservatoires locaux) — liste non exhaustive. */
window.ELAG_VARIETES={
 intro:'L’Ariège garde un beau patrimoine fruitier, mais dispersé de vallée en vallée. Voici quelques variétés documentées et, surtout, les conservatoires qui les sauvegardent — la vraie référence si tu cherches un plant greffé du pays.',
 varietes:[
  {n:'Reinette de l’Ariège', ic:'🍎', type:'Pomme locale', desc:'Pomme assez grosse, juteuse, acidulée, bien sucrée et parfumée. À couteau comme en cuisine, se garde bien l’hiver.'},
  {n:'Pomme de Pouzac', ic:'🍎', type:'Pomme du piémont pyrénéen', desc:'Originaire de Pouzac (piémont, Hautes-Pyrénées) mais présente dans tout le Massif : chair dense, croquante, très sucrée et parfumée. Excellente pomme à couteau.'},
  {n:'Guin noir d’Ariège', ic:'🍒', type:'Guigne / cerise noire', desc:'Petite cerise (guigne) noire ariégeoise, sucrée. À déguster, en confiture et en eau-de-vie.'},
  {n:'Reinettes de pays (grise, clochard…)', ic:'🍏', type:'Pommes de garde', desc:'Vieilles reinettes rustiques du piémont : chair ferme, acidulée, parfumée, excellente conservation. Le cœur des vergers d’autrefois.'},
  {n:'Pommes à jus & à cidre', ic:'🧃', type:'Pommes rustiques', desc:'Variétés rustiques pressées en jus fermier (fermes de Foix, du Couserans). Souvent acidulées ou amères, parfaites en assemblage.'},
  {n:'Poires à cuire anciennes', ic:'🍐', type:'Poires de conservation', desc:'Poires fermes d’hiver, à pocher ou en compote, qui se gardent longtemps au fruitier. Nombreuses variétés locales.'},
  {n:'Prunes du pays (reine-claude, prune d’ente)', ic:'🫐', type:'Prunes locales', desc:'Prunes rustiques pour la table, la confiture et le séchage (pruneaux). Le prunier se ressème et se transmet de jardin en jardin.'},
  {n:'Figuiers de pays', ic:'🌿', type:'Figues des jardins', desc:'Vieux figuiers des jardins ariégeois abrités, souvent bifères (figues-fleurs en été, figues d’automne). Bouturés de voisin à voisin.'}
 ],
 conservatoires:[
  {n:'Atout Fruit', lieu:'Vallée de l’Hers (Léran, 09)', quoi:'Étude, sauvegarde et greffons des variétés locales ; chantiers de taille douce. LA référence du secteur.'},
  {n:'Apiun e Coutera', lieu:'Couserans (09)', quoi:'Conservation et valorisation des fruitiers locaux du Couserans.'},
  {n:'Ferme de Bacala', lieu:'Ariège', quoi:'Pépinière de fruitiers anciens, souvent pyrénéens (pommiers, pruniers, abricotiers, amandiers).'},
  {n:'Nature et Verger', lieu:'Haute-Ariège', quoi:'Pépinière fruitière de variétés anciennes et rustiques d’altitude.'},
  {n:'Les Jardins du Terroir', lieu:'Mercenac (09)', quoi:'Verger conservatoire (une trentaine de variétés de pommes anciennes et locales).'},
  {n:'Ferme de Mailhac', lieu:'Foix (09)', quoi:'Vergers de pommes anciennes en bio, jus de fruits fermier.'}
 ]
};
