/* occitan_phrases.js — Dictionnaire de phrases occitan (languedocien) → français.
   Consommé par app.js (renderOccitanPhrases) ; injecté par assemble.js.
   o = occitan (norma classica, lengadocian) · f = français. */
window.OCCITAN_PHRASES=[
{cat:'Saluer & politesse', ic:'👋', items:[
 {o:'Adieu !', f:'Salut ! (bonjour et au revoir, entre proches)'},
 {o:'Adiu !', f:'Salut ! (variante)'},
 {o:'Bonjorn !', f:'Bonjour !'},
 {o:'Adieusiatz !', f:'Bonjour ! (poli / à plusieurs)'},
 {o:'Bon vèspre !', f:'Bonsoir !'},
 {o:'Bona nuèch !', f:'Bonne nuit !'},
 {o:'A reveire !', f:'Au revoir !'},
 {o:'A lèu !', f:'À bientôt !'},
 {o:'A deman !', f:'À demain !'},
 {o:'A la revista !', f:'À la prochaine !'},
 {o:'Mercé !', f:'Merci !'},
 {o:'Mercé plan !', f:'Merci beaucoup !'},
 {o:'De ren !', f:'De rien !'},
 {o:'Se vos plai !', f:'S’il te/vous plaît !'},
 {o:'Perdon !', f:'Pardon !'},
 {o:'Bon vent !', f:'Bonne route ! Bon voyage !'},
 {o:'Bona jornada !', f:'Bonne journée !'},
 {o:'Bona serada !', f:'Bonne soirée !'},
 {o:'Bon coratge !', f:'Bon courage !'},
 {o:'Salut a l’ostal !', f:'Le bonjour à la maison / à la famille !'}
]},
{cat:'Se présenter', ic:'🙋', items:[
 {o:'Cossí te dises ?', f:'Comment t’appelles-tu ?'},
 {o:'Me disi…', f:'Je m’appelle…'},
 {o:'D’ont sès ?', f:'D’où es-tu ?'},
 {o:'Soi de Pàmias.', f:'Je suis de Pamiers.'},
 {o:'Demòri a Foish.', f:'J’habite à Foix.'},
 {o:'Quin atge as ?', f:'Quel âge as-tu ?'},
 {o:'Ai trenta ans.', f:'J’ai trente ans.'},
 {o:'Apreni l’occitan.', f:'J’apprends l’occitan.'},
 {o:'Parli pas plan occitan.', f:'Je ne parle pas bien occitan.'},
 {o:'Parli un pauc occitan.', f:'Je parle un peu occitan.'},
 {o:'Plan content de te veire !', f:'Content de te voir !'},
 {o:'E tu ?', f:'Et toi ?'}
]},
{cat:'Comment ça va', ic:'🙂', items:[
 {o:'Cossí va ?', f:'Comment ça va ?'},
 {o:'Cossí anatz ?', f:'Comment allez-vous ? (poli)'},
 {o:'Va plan.', f:'Ça va bien.'},
 {o:'Va plan, mercé.', f:'Ça va bien, merci.'},
 {o:'Va pas tròp.', f:'Ça ne va pas trop.'},
 {o:'Va comme aquò.', f:'Ça va comme ça / couci-couça.'},
 {o:'Soi las.', f:'Je suis fatigué.'},
 {o:'Soi lassa.', f:'Je suis fatiguée.'},
 {o:'Ai fam.', f:'J’ai faim.'},
 {o:'Ai set.', f:'J’ai soif.'},
 {o:'Tot va plan a l’ostal ?', f:'Tout va bien à la maison ?'}
]},
{cat:'Au café, à table', ic:'☕', items:[
 {o:'Vòli un cafè, se vos plai.', f:'Je voudrais un café, s’il vous plaît.'},
 {o:'Un veire de vin, se vos plai.', f:'Un verre de vin, s’il vous plaît.'},
 {o:'Una cana de bièrra.', f:'Une chope de bière.'},
 {o:'Un veire d’aiga.', f:'Un verre d’eau.'},
 {o:'Qué prenètz ?', f:'Que prenez-vous ?'},
 {o:'Es a ieu !', f:'C’est ma tournée !'},
 {o:'A la vòstra !', f:'À la vôtre !'},
 {o:'A la tieuna !', f:'À la tienne !'},
 {o:'Es bon !', f:'C’est bon !'},
 {o:'Aquò èra fòrça bon.', f:'C’était très bon.'},
 {o:'L’addicion, se vos plai.', f:'L’addition, s’il vous plaît.'},
 {o:'Bon apetís !', f:'Bon appétit !'}
]},
{cat:'Au marché, acheter', ic:'🛒', items:[
 {o:'Quant còsta ?', f:'Combien ça coûte ?'},
 {o:'Quant vos devi ?', f:'Combien je vous dois ?'},
 {o:'Es tròp car.', f:'C’est trop cher.'},
 {o:'Me’n donatz un quilò ?', f:'Vous m’en donnez un kilo ?'},
 {o:'Ne vòli mièg quilò.', f:'J’en veux une demi-livre.'},
 {o:'Avètz de pan ?', f:'Avez-vous du pain ?'},
 {o:'Es fresc ?', f:'C’est frais ?'},
 {o:'Ne preni dos.', f:'J’en prends deux.'},
 {o:'Aquò’s tot, mercé.', f:'C’est tout, merci.'},
 {o:'Me fasètz un prètz ?', f:'Vous me faites un prix ?'},
 {o:'Pagui en liquid.', f:'Je paie en liquide.'},
 {o:'Avètz la moneda ?', f:'Avez-vous la monnaie ?'}
]},
{cat:'Demander son chemin', ic:'🧭', items:[
 {o:'Ont es… ?', f:'Où est… ?'},
 {o:'Ont son los banhs ?', f:'Où sont les toilettes ?'},
 {o:'Es luènh ?', f:'C’est loin ?'},
 {o:'Es a costat.', f:'C’est à côté.'},
 {o:'Tot drech.', f:'Tout droit.'},
 {o:'A drecha.', f:'À droite.'},
 {o:'A esquèrra.', f:'À gauche.'},
 {o:'Viratz a drecha.', f:'Tournez à droite.'},
 {o:'Perdon, cerqui la gara.', f:'Pardon, je cherche la gare.'},
 {o:'Me podètz ajudar ?', f:'Pouvez-vous m’aider ?'},
 {o:'Ont mena aquesta rota ?', f:'Où mène cette route ?'}
]},
{cat:'Le temps qu’il fait', ic:'🌦️', items:[
 {o:'Quin temps fa ?', f:'Quel temps fait-il ?'},
 {o:'Fa bèl.', f:'Il fait beau.'},
 {o:'Fa laid.', f:'Il fait mauvais.'},
 {o:'Fa calor.', f:'Il fait chaud.'},
 {o:'Fa freg.', f:'Il fait froid.'},
 {o:'Plòu.', f:'Il pleut.'},
 {o:'Nèva.', f:'Il neige.'},
 {o:'Fa de vent.', f:'Il y a du vent.'},
 {o:'Lo solelh se lèva.', f:'Le soleil se lève.'}
]},
{cat:'Heure, jours, moments', ic:'🕰️', items:[
 {o:'Quina ora es ?', f:'Quelle heure est-il ?'},
 {o:'Es mièjorn.', f:'Il est midi.'},
 {o:'Es mièjanuèch.', f:'Il est minuit.'},
 {o:'Uèi.', f:'Aujourd’hui.'},
 {o:'Deman.', f:'Demain.'},
 {o:'Ièr.', f:'Hier.'},
 {o:'Ara.', f:'Maintenant.'},
 {o:'Deman de matin.', f:'Demain matin.'},
 {o:'Aqueste ser.', f:'Ce soir.'},
 {o:'La setmana que ven.', f:'La semaine prochaine.'},
 {o:'Es ora d’anar.', f:'Il est l’heure d’y aller.'}
]},
{cat:'Ressentir & réagir', ic:'💬', items:[
 {o:'Soi content.', f:'Je suis content.'},
 {o:'Soi contenta.', f:'Je suis contente.'},
 {o:'Soi triste.', f:'Je suis triste.'},
 {o:'M’agrada.', f:'Ça me plaît.'},
 {o:'M’agrada pas.', f:'Ça ne me plaît pas.'},
 {o:'Aimi aquò !', f:'J’aime ça !'},
 {o:'Qué bèl !', f:'Que c’est beau !'},
 {o:'Qué brave !', f:'Comme c’est gentil / bien !'},
 {o:'Soi d’acòrd.', f:'Je suis d’accord.'},
 {o:'Crési que òc.', f:'Je crois que oui.'},
 {o:'Crési que non.', f:'Je crois que non.'},
 {o:'Es pas grèu.', f:'Ce n’est pas grave.'}
]},
{cat:'Comprendre & se dépanner', ic:'🆘', items:[
 {o:'Compreni pas.', f:'Je ne comprends pas.'},
 {o:'Ausi pas plan.', f:'Je n’entends pas bien.'},
 {o:'Podètz tornar dire ?', f:'Pouvez-vous répéter ?'},
 {o:'Mai doçament, se vos plai.', f:'Plus doucement, s’il vous plaît.'},
 {o:'Cossí se ditz… en occitan ?', f:'Comment dit-on… en occitan ?'},
 {o:'Qué vòl dire aquò ?', f:'Qu’est-ce que ça veut dire ?'},
 {o:'Cossí s’escriu ?', f:'Comment ça s’écrit ?'},
 {o:'Ai besonh d’ajuda.', f:'J’ai besoin d’aide.'},
 {o:'Ajuda !', f:'À l’aide !'},
 {o:'Sonatz los pompièrs !', f:'Appelez les pompiers !'}
]},
{cat:'Bavarder de tout', ic:'🗣️', items:[
 {o:'Qué de nòu ?', f:'Quoi de neuf ?'},
 {o:'Res de nòu.', f:'Rien de neuf.'},
 {o:'Qué fas de bon ?', f:'Qu’est-ce que tu fais de beau ?'},
 {o:'Trabalhi.', f:'Je travaille.'},
 {o:'Soi en vacanças.', f:'Je suis en vacances.'},
 {o:'Diga-me.', f:'Dis-moi.'},
 {o:'Escota.', f:'Écoute.'},
 {o:'Es verai ?', f:'C’est vrai ?'},
 {o:'De segur !', f:'Bien sûr !'},
 {o:'Nos veirem lèu.', f:'On se verra bientôt.'},
 {o:'Passa lo bonjorn a…', f:'Passe le bonjour à…'}
]},
{cat:'Proverbes & expressions', ic:'🌿', items:[
 {o:'Pauc a pauc l’aucèl fa son nis.', f:'Petit à petit l’oiseau fait son nid.'},
 {o:'Qual language perd, sa arma perd.', f:'Qui perd sa langue perd son âme.'},
 {o:'Val mai tard que jamai.', f:'Mieux vaut tard que jamais.'},
 {o:'Qui vòl, pòt.', f:'Qui veut, peut.'},
 {o:'Paciéncia e longor de temps.', f:'Patience et longueur de temps.'},
 {o:'Ben far e daissar dire.', f:'Bien faire et laisser dire.'},
 {o:'L’aiga va totjorn a la mar.', f:'L’eau va toujours à la mer.'},
 {o:'Cada aucèl tròba son nis brave.', f:'Chaque oiseau trouve son nid beau.'},
 {o:'Qui s’i fròta s’i pica.', f:'Qui s’y frotte s’y pique.'},
 {o:'A cada jorn sufís sa pena.', f:'À chaque jour suffit sa peine.'}
]}
];
