/* occitan_phrases.js — Dictionnaire de phrases occitan (languedocien) → français.
   Consommé par app.js (renderOccitanPhrases) ; injecté par assemble.js.
   o = occitan (norma classica, lengadocian) · f = français. */
window.OCCITAN_PHRASES=[
{cat:'Saluer & politesse', ic:'👋', items:[
 {o:'Adieu !', f:'Salut ! (bonjour et au revoir, entre proches)'},
 {o:'Adiu !', f:'Salut ! (variante)'},
 {o:'Bonjorn !', f:'Bonjour !'},
 {o:'Adieusiatz !', f:'Bonjour ! (poli / à plusieurs)'},
 {o:'Bon vèspre !', f:'Bonsoir !'},
 {o:'Bona nuèch !', f:'Bonne nuit !'},
 {o:'A reveire !', f:'Au revoir !'},
 {o:'A lèu !', f:'À bientôt !'},
 {o:'A deman !', f:'À demain !'},
 {o:'A la revista !', f:'À la prochaine !'},
 {o:'Mercé !', f:'Merci !'},
 {o:'Mercé plan !', f:'Merci beaucoup !'},
 {o:'De ren !', f:'De rien !'},
 {o:'Se vos plai !', f:'S’il te/vous plaît !'},
 {o:'Perdon !', f:'Pardon !'},
 {o:'Bon vent !', f:'Bonne route ! Bon voyage !'},
 {o:'Bona jornada !', f:'Bonne journée !'},
 {o:'Bona serada !', f:'Bonne soirée !'},
 {o:'Bon coratge !', f:'Bon courage !'},
 {o:'Salut a l’ostal !', f:'Le bonjour à la maison / à la famille !'}
]},
{cat:'Se présenter', ic:'🙋', items:[
 {o:'Cossí te dises ?', f:'Comment t’appelles-tu ?'},
 {o:'Me disi…', f:'Je m’appelle…'},
 {o:'D’ont sès ?', f:'D’où es-tu ?'},
 {o:'Soi de Pàmias.', f:'Je suis de Pamiers.'},
 {o:'Demòri a Foish.', f:'J’habite à Foix.'},
 {o:'Quin atge as ?', f:'Quel âge as-tu ?'},
 {o:'Ai trenta ans.', f:'J’ai trente ans.'},
 {o:'Apreni l’occitan.', f:'J’apprends l’occitan.'},
 {o:'Parli pas plan occitan.', f:'Je ne parle pas bien occitan.'},
 {o:'Parli un pauc occitan.', f:'Je parle un peu occitan.'},
 {o:'Plan content de te veire !', f:'Content de te voir !'},
 {o:'E tu ?', f:'Et toi ?'}
]},
{cat:'Comment ça va', ic:'🙂', items:[
 {o:'Cossí va ?', f:'Comment ça va ?'},
 {o:'Cossí anatz ?', f:'Comment allez-vous ? (poli)'},
 {o:'Va plan.', f:'Ça va bien.'},
 {o:'Va plan, mercé.', f:'Ça va bien, merci.'},
 {o:'Va pas tròp.', f:'Ça ne va pas trop.'},
 {o:'Va comme aquò.', f:'Ça va comme ça / couci-couça.'},
 {o:'Soi las.', f:'Je suis fatigué.'},
 {o:'Soi lassa.', f:'Je suis fatiguée.'},
 {o:'Ai fam.', f:'J’ai faim.'},
 {o:'Ai set.', f:'J’ai soif.'},
 {o:'Tot va plan a l’ostal ?', f:'Tout va bien à la maison ?'}
]},
{cat:'Au café, à table', ic:'☕', items:[
 {o:'Vòli un cafè, se vos plai.', f:'Je voudrais un café, s’il vous plaît.'},
 {o:'Un veire de vin, se vos plai.', f:'Un verre de vin, s’il vous plaît.'},
 {o:'Una cana de bièrra.', f:'Une chope de bière.'},
 {o:'Un veire d’aiga.', f:'Un verre d’eau.'},
 {o:'Qué prenètz ?', f:'Que prenez-vous ?'},
 {o:'Es a ieu !', f:'C’est ma tournée !'},
 {o:'A la vòstra !', f:'À la vôtre !'},
 {o:'A la tieuna !', f:'À la tienne !'},
 {o:'Es bon !', f:'C’est bon !'},
 {o:'Aquò èra fòrça bon.', f:'C’était très bon.'},
 {o:'L’addicion, se vos plai.', f:'L’addition, s’il vous plaît.'},
 {o:'Bon apetís !', f:'Bon appétit !'}
]},
{cat:'Au marché, acheter', ic:'🛒', items:[
 {o:'Quant còsta ?', f:'Combien ça coûte ?'},
 {o:'Quant vos devi ?', f:'Combien je vous dois ?'},
 {o:'Es tròp car.', f:'C’est trop cher.'},
 {o:'Me’n donatz un quilò ?', f:'Vous m’en donnez un kilo ?'},
 {o:'Ne vòli mièg quilò.', f:'J’en veux une demi-livre.'},
 {o:'Avètz de pan ?', f:'Avez-vous du pain ?'},
 {o:'Es fresc ?', f:'C’est frais ?'},
 {o:'Ne preni dos.', f:'J’en prends deux.'},
 {o:'Aquò’s tot, mercé.', f:'C’est tout, merci.'},
 {o:'Me fasètz un prètz ?', f:'Vous me faites un prix ?'},
 {o:'Pagui en liquid.', f:'Je paie en liquide.'},
 {o:'Avètz la moneda ?', f:'Avez-vous la monnaie ?'}
]},
{cat:'Demander son chemin', ic:'🧭', items:[
 {o:'Ont es… ?', f:'Où est… ?'},
 {o:'Ont son los banhs ?', f:'Où sont les toilettes ?'},
 {o:'Es luènh ?', f:'C’est loin ?'},
 {o:'Es a costat.', f:'C’est à côté.'},
 {o:'Tot drech.', f:'Tout droit.'},
 {o:'A drecha.', f:'À droite.'},
 {o:'A esquèrra.', f:'À gauche.'},
 {o:'Viratz a drecha.', f:'Tournez à droite.'},
 {o:'Perdon, cerqui la gara.', f:'Pardon, je cherche la gare.'},
 {o:'Me podètz ajudar ?', f:'Pouvez-vous m’aider ?'},
 {o:'Ont mena aquesta rota ?', f:'Où mène cette route ?'}
]},
{cat:'Le temps qu’il fait', ic:'🌦️', items:[
 {o:'Quin temps fa ?', f:'Quel temps fait-il ?'},
 {o:'Fa bèl.', f:'Il fait beau.'},
 {o:'Fa laid.', f:'Il fait mauvais.'},
 {o:'Fa calor.', f:'Il fait chaud.'},
 {o:'Fa freg.', f:'Il fait froid.'},
 {o:'Plòu.', f:'Il pleut.'},
 {o:'Nèva.', f:'Il neige.'},
 {o:'Fa de vent.', f:'Il y a du vent.'},
 {o:'Lo solelh se lèva.', f:'Le soleil se lève.'}
]},
{cat:'Heure, jours, moments', ic:'🕰️', items:[
 {o:'Quina ora es ?', f:'Quelle heure est-il ?'},
 {o:'Es mièjorn.', f:'Il est midi.'},
 {o:'Es mièjanuèch.', f:'Il est minuit.'},
 {o:'Uèi.', f:'Aujourd’hui.'},
 {o:'Deman.', f:'Demain.'},
 {o:'Ièr.', f:'Hier.'},
 {o:'Ara.', f:'Maintenant.'},
 {o:'Deman de matin.', f:'Demain matin.'},
 {o:'Aqueste ser.', f:'Ce soir.'},
 {o:'La setmana que ven.', f:'La semaine prochaine.'},
 {o:'Es ora d’anar.', f:'Il est l’heure d’y aller.'}
]},
{cat:'Ressentir & réagir', ic:'💬', items:[
 {o:'Soi content.', f:'Je suis content.'},
 {o:'Soi contenta.', f:'Je suis contente.'},
 {o:'Soi triste.', f:'Je suis triste.'},
 {o:'M’agrada.', f:'Ça me plaît.'},
 {o:'M’agrada pas.', f:'Ça ne me plaît pas.'},
 {o:'Aimi aquò !', f:'J’aime ça !'},
 {o:'Qué bèl !', f:'Que c’est beau !'},
 {o:'Qué brave !', f:'Comme c’est gentil / bien !'},
 {o:'Soi d’acòrd.', f:'Je suis d’accord.'},
 {o:'Crési que òc.', f:'Je crois que oui.'},
 {o:'Crési que non.', f:'Je crois que non.'},
 {o:'Es pas grèu.', f:'Ce n’est pas grave.'}
]},
{cat:'Comprendre & se dépanner', ic:'🆘', items:[
 {o:'Compreni pas.', f:'Je ne comprends pas.'},
 {o:'Ausi pas plan.', f:'Je n’entends pas bien.'},
 {o:'Podètz tornar dire ?', f:'Pouvez-vous répéter ?'},
 {o:'Mai doçament, se vos plai.', f:'Plus doucement, s’il vous plaît.'},
 {o:'Cossí se ditz… en occitan ?', f:'Comment dit-on… en occitan ?'},
 {o:'Qué vòl dire aquò ?', f:'Qu’est-ce que ça veut dire ?'},
 {o:'Cossí s’escriu ?', f:'Comment ça s’écrit ?'},
 {o:'Ai besonh d’ajuda.', f:'J’ai besoin d’aide.'},
 {o:'Ajuda !', f:'À l’aide !'},
 {o:'Sonatz los pompièrs !', f:'Appelez les pompiers !'}
]},
{cat:'Bavarder de tout', ic:'🗣️', items:[
 {o:'Qué de nòu ?', f:'Quoi de neuf ?'},
 {o:'Res de nòu.', f:'Rien de neuf.'},
 {o:'Qué fas de bon ?', f:'Qu’est-ce que tu fais de beau ?'},
 {o:'Trabalhi.', f:'Je travaille.'},
 {o:'Soi en vacanças.', f:'Je suis en vacances.'},
 {o:'Diga-me.', f:'Dis-moi.'},
 {o:'Escota.', f:'Écoute.'},
 {o:'Es verai ?', f:'C’est vrai ?'},
 {o:'De segur !', f:'Bien sûr !'},
 {o:'Nos veirem lèu.', f:'On se verra bientôt.'},
 {o:'Passa lo bonjorn a…', f:'Passe le bonjour à…'}
]},
{cat:'Proverbes & expressions', ic:'🌿', items:[
 {o:'Pauc a pauc l’aucèl fa son nis.', f:'Petit à petit l’oiseau fait son nid.'},
 {o:'Qual language perd, sa arma perd.', f:'Qui perd sa langue perd son âme.'},
 {o:'Val mai tard que jamai.', f:'Mieux vaut tard que jamais.'},
 {o:'Qui vòl, pòt.', f:'Qui veut, peut.'},
 {o:'Paciéncia e longor de temps.', f:'Patience et longueur de temps.'},
 {o:'Ben far e daissar dire.', f:'Bien faire et laisser dire.'},
 {o:'L’aiga va totjorn a la mar.', f:'L’eau va toujours à la mer.'},
 {o:'Cada aucèl tròba son nis brave.', f:'Chaque oiseau trouve son nid beau.'},
 {o:'Qui s’i fròta s’i pica.', f:'Qui s’y frotte s’y pique.'},
 {o:'A cada jorn sufís sa pena.', f:'À chaque jour suffit sa peine.'}
]},
{cat:'Les questions utiles', ic:'❓', items:[
 {o:'Qual ?', f:'Qui ?'},
 {o:'Qué ?', f:'Quoi ?'},
 {o:'Ont ?', f:'Où ?'},
 {o:'Quora ?', f:'Quand ?'},
 {o:'Perqué ?', f:'Pourquoi ?'},
 {o:'Cossí ?', f:'Comment ?'},
 {o:'Quant ?', f:'Combien ?'},
 {o:'Quin ? / Quina ?', f:'Quel ? / Quelle ?'},
 {o:'De qual es aquò ?', f:'À qui est-ce ?'},
 {o:'Perqué pas ?', f:'Pourquoi pas ?'},
 {o:'Amb qual ?', f:'Avec qui ?'},
 {o:'Cap ont ?', f:'Vers où ?'}
]},
{cat:'Petits mots & liaisons', ic:'🔗', items:[
 {o:'e', f:'et'},
 {o:'mas', f:'mais'},
 {o:'o', f:'ou'},
 {o:'doncas', f:'donc'},
 {o:'alara', f:'alors'},
 {o:'perque', f:'parce que'},
 {o:'puèi', f:'puis, ensuite'},
 {o:'tanben', f:'aussi'},
 {o:'pr’aquò', f:'pourtant'},
 {o:'amb', f:'avec'},
 {o:'sens', f:'sans'},
 {o:'encara', f:'encore'},
 {o:'jamai', f:'jamais'},
 {o:'totjorn', f:'toujours'}
]},
{cat:'Nombres & quantités', ic:'🔢', items:[
 {o:'un, dos, tres', f:'un, deux, trois'},
 {o:'quatre, cinc, sièis', f:'quatre, cinq, six'},
 {o:'sèt, uèch, nòu, dètz', f:'sept, huit, neuf, dix'},
 {o:'vint, trenta, quaranta', f:'vingt, trente, quarante'},
 {o:'cent, mila', f:'cent, mille'},
 {o:'lo primièr', f:'le premier'},
 {o:'lo darrièr', f:'le dernier'},
 {o:'fòrça', f:'beaucoup'},
 {o:'un pauc', f:'un peu'},
 {o:'pas gaire', f:'guère, pas beaucoup'},
 {o:'pro', f:'assez'},
 {o:'tròp', f:'trop'},
 {o:'la mitat', f:'la moitié'},
 {o:'un tròç', f:'un morceau'}
]},
{cat:'Les couleurs', ic:'🎨', items:[
 {o:'De quina color es ?', f:'De quelle couleur est-ce ?'},
 {o:'roge', f:'rouge'},
 {o:'blau', f:'bleu'},
 {o:'verd', f:'vert'},
 {o:'jaune', f:'jaune'},
 {o:'blanc', f:'blanc'},
 {o:'negre', f:'noir'},
 {o:'gris', f:'gris'},
 {o:'marron', f:'marron'},
 {o:'ròse', f:'rose'},
 {o:'irange', f:'orange'}
]},
{cat:'Le corps & la santé', ic:'🩺', items:[
 {o:'lo cap', f:'la tête'},
 {o:'la man', f:'la main'},
 {o:'lo braç', f:'le bras'},
 {o:'la camba', f:'la jambe'},
 {o:'lo pè', f:'le pied'},
 {o:'los uèlhs', f:'les yeux'},
 {o:'lo ventre', f:'le ventre'},
 {o:'Ai mal al cap.', f:'J’ai mal à la tête.'},
 {o:'Ai mal a las dents.', f:'J’ai mal aux dents.'},
 {o:'Soi malaut.', f:'Je suis malade.'},
 {o:'Me senti pas plan.', f:'Je ne me sens pas bien.'},
 {o:'Ont es lo mètge ?', f:'Où est le médecin ?'},
 {o:'Garís-te lèu !', f:'Guéris vite !'}
]},
{cat:'Manger & cuisiner', ic:'🍲', items:[
 {o:'Qué manjam ?', f:'Qu’est-ce qu’on mange ?'},
 {o:'la sopa', f:'la soupe'},
 {o:'la carn', f:'la viande'},
 {o:'lo peis', f:'le poisson'},
 {o:'los legums', f:'les légumes'},
 {o:'la poma', f:'la pomme'},
 {o:'l’uòu', f:'l’œuf'},
 {o:'lo lach', f:'le lait'},
 {o:'la mèl', f:'le miel'},
 {o:'Es cuèch.', f:'C’est cuit.'},
 {o:'Es crut.', f:'C’est cru.'},
 {o:'Manja plan !', f:'Mange bien !'},
 {o:'Sèrve-te !', f:'Sers-toi !'}
]},
{cat:'La maison', ic:'🏠', items:[
 {o:'l’ostal', f:'la maison'},
 {o:'la pòrta', f:'la porte'},
 {o:'la fenèstra', f:'la fenêtre'},
 {o:'la taula', f:'la table'},
 {o:'la cadièra', f:'la chaise'},
 {o:'lo lièch', f:'le lit'},
 {o:'la cosina', f:'la cuisine'},
 {o:'lo fuòc', f:'le feu, l’âtre'},
 {o:'Dubrís la pòrta.', f:'Ouvre la porte.'},
 {o:'Barra la fenèstra.', f:'Ferme la fenêtre.'},
 {o:'Vèni a l’ostal.', f:'Viens à la maison.'},
 {o:'Soi a l’ostal.', f:'Je suis à la maison.'}
]},
{cat:'À la ferme & les bêtes', ic:'🐄', items:[
 {o:'la vaca', f:'la vache'},
 {o:'lo buòu', f:'le bœuf'},
 {o:'lo pòrc', f:'le cochon'},
 {o:'la feda', f:'la brebis'},
 {o:'l’anhèl', f:'l’agneau'},
 {o:'la galina', f:'la poule'},
 {o:'lo caval', f:'le cheval'},
 {o:'l’ase', f:'l’âne'},
 {o:'la cabra', f:'la chèvre'},
 {o:'Lo can garda las fedas.', f:'Le chien garde les brebis.'},
 {o:'Cal mólzer las vacas.', f:'Il faut traire les vaches.'},
 {o:'Las galinas ponon.', f:'Les poules pondent.'}
]},
{cat:'Le bois & la forêt', ic:'🌲', items:[
 {o:'l’arbre', f:'l’arbre'},
 {o:'lo bòsc', f:'le bois, la forêt'},
 {o:'la branca', f:'la branche'},
 {o:'la fuèlha', f:'la feuille'},
 {o:'la rusca', f:'l’écorce'},
 {o:'lo garric', f:'le chêne'},
 {o:'lo fau', f:'le hêtre'},
 {o:'lo pin', f:'le pin'},
 {o:'lo castanhièr', f:'le châtaignier'},
 {o:'Copar de bòsc.', f:'Couper du bois.'},
 {o:'Fendre la lenha.', f:'Fendre le bois de chauffage.'},
 {o:'Talhar un arbre.', f:'Tailler / abattre un arbre.'}
]},
{cat:'La nature & les Pyrénées', ic:'⛰️', items:[
 {o:'la montanha', f:'la montagne'},
 {o:'lo puèg', f:'le sommet, le pic'},
 {o:'la val', f:'la vallée'},
 {o:'lo riu', f:'le ruisseau'},
 {o:'la ribièra', f:'la rivière'},
 {o:'lo prat', f:'le pré'},
 {o:'lo camp', f:'le champ'},
 {o:'las Pirenèas', f:'les Pyrénées'},
 {o:'Lo cèl es blau.', f:'Le ciel est bleu.'},
 {o:'L’aucèl canta.', f:'L’oiseau chante.'},
 {o:'Fa bon dins lo bòsc.', f:'Il fait bon dans les bois.'},
 {o:'La nèu sus la montanha.', f:'La neige sur la montagne.'}
]},
{cat:'Saisons & moments', ic:'🍂', items:[
 {o:'la prima', f:'le printemps'},
 {o:'l’estiu', f:'l’été'},
 {o:'l’automne', f:'l’automne'},
 {o:'l’ivèrn', f:'l’hiver'},
 {o:'lo matin', f:'le matin'},
 {o:'lo vèspre', f:'le soir'},
 {o:'Fa calor en estiu.', f:'Il fait chaud en été.'},
 {o:'Nèva en ivèrn.', f:'Il neige en hiver.'},
 {o:'Las fuèlhas tomban.', f:'Les feuilles tombent.'},
 {o:'Lo temps se met al bèl.', f:'Le temps se met au beau.'}
]},
{cat:'Sur la route, en voiture', ic:'🚗', items:[
 {o:'la rota', f:'la route'},
 {o:'la veitura', f:'la voiture'},
 {o:'lo camion', f:'le camion'},
 {o:'Anar a pè.', f:'Aller à pied.'},
 {o:'Prene lo bus.', f:'Prendre le bus.'},
 {o:'Ont vas ?', f:'Où vas-tu ?'},
 {o:'Vau a Tolosa.', f:'Je vais à Toulouse.'},
 {o:'Menar.', f:'Conduire.'},
 {o:'Atencion !', f:'Attention !'},
 {o:'Anem-i !', f:'Allons-y !'},
 {o:'Sèm arribats.', f:'Nous sommes arrivés.'}
]},
{cat:'Le travail & les métiers', ic:'🛠️', items:[
 {o:'lo trabalh', f:'le travail'},
 {o:'Ai fòrça trabalh.', f:'J’ai beaucoup de travail.'},
 {o:'lo mestièr', f:'le métier'},
 {o:'lo pagès', f:'le paysan'},
 {o:'lo fustièr', f:'le menuisier'},
 {o:'lo bocatièr', f:'le bûcheron'},
 {o:'lo mecanician', f:'le mécanicien'},
 {o:'las aisinas', f:'les outils'},
 {o:'Ai acabat.', f:'J’ai fini.'},
 {o:'Cal o far.', f:'Il faut le faire.'},
 {o:'Es un bon trabalh.', f:'C’est du bon travail.'},
 {o:'Bon coratge al trabalh !', f:'Bon courage au travail !'}
]},
{cat:'Apprendre & à l’école', ic:'📚', items:[
 {o:'Apréni.', f:'J’apprends.'},
 {o:'Ensenhar.', f:'Enseigner.'},
 {o:'Legir.', f:'Lire.'},
 {o:'Escriure.', f:'Écrire.'},
 {o:'un libre', f:'un livre'},
 {o:'un mot', f:'un mot'},
 {o:'Tòrna dire, se vos plai.', f:'Répète, s’il te plaît.'},
 {o:'Ai comprés !', f:'J’ai compris !'},
 {o:'Es aisit.', f:'C’est facile.'},
 {o:'Es malaisit.', f:'C’est difficile.'},
 {o:'Cossí s’escriu aquel mot ?', f:'Comment s’écrit ce mot ?'}
]},
{cat:'Faire connaissance & se voir', ic:'🤝', items:[
 {o:'Vòles venir ?', f:'Tu veux venir ?'},
 {o:'Ont nos vejam ?', f:'Où est-ce qu’on se voit ?'},
 {o:'A quina ora ?', f:'À quelle heure ?'},
 {o:'Sès liure deman ?', f:'Tu es libre demain ?'},
 {o:'Anem beure un còp !', f:'Allons boire un coup !'},
 {o:'T’aimi plan.', f:'Je t’aime bien.'},
 {o:'Sès brave.', f:'Tu es gentil.'},
 {o:'Nos telefonam.', f:'On s’appelle.'},
 {o:'D’acòrd, a lèu !', f:'D’accord, à bientôt !'},
 {o:'Es un plaser.', f:'C’est un plaisir.'}
]},
{cat:'Caractère & jugement', ic:'🧑', items:[
 {o:'Es brave.', f:'Il est gentil.'},
 {o:'Es marrit.', f:'Il est méchant.'},
 {o:'Es trabalhaire.', f:'Il est travailleur.'},
 {o:'Es feniant.', f:'Il est paresseux.'},
 {o:'Es fòl.', f:'Il est fou.'},
 {o:'Es plan brave.', f:'Il est très gentil.'},
 {o:'Ai paur.', f:'J’ai peur.'},
 {o:'Soi fièr.', f:'Je suis fier.'},
 {o:'Es coratjós.', f:'Il est courageux.'},
 {o:'Es plan plan.', f:'Il est tranquille / posé.'}
]},
{cat:'Fête, musique & traditions', ic:'🎉', items:[
 {o:'la fèsta', f:'la fête'},
 {o:'lo bal', f:'le bal'},
 {o:'Cantar.', f:'Chanter.'},
 {o:'Dançar.', f:'Danser.'},
 {o:'Toca l’acordeon !', f:'Joue de l’accordéon !'},
 {o:'Anem far la fèsta !', f:'Allons faire la fête !'},
 {o:'Viva l’Occitània !', f:'Vive l’Occitanie !'},
 {o:'Cantem Se Canta !', f:'Chantons Se Canta !'},
 {o:'Es la fèsta al vilatge.', f:'C’est la fête au village.'},
 {o:'Qué polida cançon !', f:'Quelle belle chanson !'}
]},
{cat:'Exclamations & mots d’ici', ic:'💥', items:[
 {o:'Macarèl !', f:'Punaise ! Mince ! (exclamation occitane)'},
 {o:'Boudu !', f:'Bon Dieu ! (exclamation de surprise)'},
 {o:'Milodiu !', f:'Nom d’un chien ! (juron doux)'},
 {o:'Bofre !', f:'Bigre ! Oh là là !'},
 {o:'Qué còp !', f:'Quelle histoire ! Quel coup !'},
 {o:'Es pas possible !', f:'Ce n’est pas possible !'},
 {o:'Vai plan !', f:'Doucement ! Tout doux !'},
 {o:'Adiu, paure !', f:'Salut, mon pauvre ! (affectueux)'},
 {o:'Qu’es aquò ?!', f:'Qu’est-ce que c’est que ça ?!'},
 {o:'Damàs !', f:'Dommage !'}
]}
];
